import PostHogPageView from "@/components/PostHogPageView";
import { Navbar } from "@/components/layout/navbar";
import type { Metadata } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import "@/lib/animations/performance.css";
import { PostHogProvider } from "./providers";

const sourceSerif = Source_Serif_4({
  variable: "--font-serif",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600"],
});

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sourceSerif.variable} antialiased`}>
        <PostHogProvider>
          <PostHogPageView />
          <Navbar />
          {children}
        </PostHogProvider>
      </body>
    </html>
  );
}
